default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: username
  password: password

development:
  <<: *default
  database: recipe-app

test:
  <<: *default
  database: recipe-app

production:
  <<: *default
  database: recipe-app
